# Generated by Django 3.2.6 on 2021-08-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_alter_productcart_customerid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcart',
            old_name='CustomerId',
            new_name='id',
        ),
    ]
