# Generated by Django 3.2.6 on 2021-08-29 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_alter_sellerproductdetails_pphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_alter_productcart_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seller.sellerproductdetails'),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='id',
            field=models.ForeignKey(default='0000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
