# Generated by Django 3.2.6 on 2021-08-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_alter_sellerproductdetails_pphoto'),
        ('Customer', '0006_alter_productcart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcart',
            name='ProductId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PId', to='Seller.sellerproductdetails'),
        ),
    ]
