# Generated by Django 3.2.6 on 2021-08-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_auto_20210829_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeedback',
            name='CustomerId',
        ),
        migrations.RemoveField(
            model_name='productfeedback',
            name='ProductId',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.DeleteModel(
            name='ProductFeedback',
        ),
    ]
