# Generated by Django 3.2.6 on 2021-08-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_sellerproductdetails_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductdetails',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellerid', to='Seller.sellerregistration'),
        ),
    ]
