# Generated by Django 3.2.6 on 2021-08-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_alter_sellerproductdetails_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerproductdetails',
            old_name='Seller',
            new_name='CompanyId',
        ),
    ]
