# Generated by Django 3.2.6 on 2021-08-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_rename_seller_sellerproductdetails_companyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductdetails',
            name='PPhoto',
            field=models.FileField(upload_to='ProductImages/'),
        ),
    ]
