# Generated by Django 3.2.6 on 2021-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_auto_20210830_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderdetails',
            name='Phonenumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productorderdetails',
            name='PinCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
